spring:
  application:
    name: uaa-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jpa:
    generate-ddl: false
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sqlMigrationPrefix: V
    sqlMigrationSeparator: __
    validateOnMigrate: true
    baselineOnMigrate: true

#????
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8500
