server:
  port: 6666
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: uaa-server
          uri: lb://uaa-server
          predicates:
            - Path=/api/uaa/**
          filters:
            - RewritePath=/api/uaa/(?<segment>.*),/$\{segment}
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: file-server
          uri: lb://file-server
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
  jpa:
    generate-ddl: false
  flyway:
    enabled: false
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #Feign的连接建立超时时间，默认为10秒
        readTimeout: 60000 #Feign的请求处理超时时间，默认为60