server:
  port: 8081


spring:
  jpa:
    generate-ddl: false
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sqlMigrationPrefix: V
    sqlMigrationSeparator: __
    validateOnMigrate: true
    baselineOnMigrate: true